[package]
name = "gelatin"
version = "0.3.0"
description = "A basic UI framework"
repository = "https://github.com/ArturKovacs/emulsion"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17"
image = "~0.23.4"
derive_builder = "0.9"
glium = { version = "0.27" }
#glutin = { version = "0.24", features=["serde"] }
