[package]
name = "gelatin"
version = "0.6.0"
description = "A basic UI framework"
repository = "https://github.com/ArturKovacs/emulsion"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17"
image = "0.23.6"
derive_builder = "0.9"
glium = { version = "0.27" }

# Forcing 0.22.0 to avoid running into
# https://github.com/rust-windowing/winit/issues/1587
# The next release that will include the fix will be 
# AFTER 0.22.2
winit = "=0.22.0" 
